REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 134 -V 5 o C:\Users\wvm405\data\logs\test\dailyactivities_alllogs_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_activitiesLT_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 108 -V 5 o "C:\Users\wvm405\data\logs\test\Hospital Billing - Event Log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_billing_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 136 -V 5 o C:\Users\wvm405\data\logs\test\BPI_Challenge_2012_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2012LT_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 58  -V 5 o C:\Users\wvm405\data\logs\test\BPI_Challenge_2013_incidents_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2013LT_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 128 -V 5 o "C:\Users\wvm405\data\logs\test\BPI2017_Challenge 2017.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2017_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 40  -V 5 o "C:\Users\wvm405\data\logs\test\DocumentProcessingENG_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_docprocLT_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 168 -V 5 o "C:\Users\wvm405\data\logs\test\dreyers_log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_dreyer_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 54  -V 5 o "C:\Users\wvm405\data\logs\test\ElectronicInvoicingENG_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_einvoicingLT_5foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 228 -V 5 o "C:\Users\wvm405\data\logs\test\nasa-cev-complete-splitted_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_nasaLT_5foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 332 -V 5 o "C:\Users\wvm405\data\logs\test\Production_Data_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_productionLT_5foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 70  -V 5 o "C:\Users\wvm405\data\logs\test\Road_Traffic_Fine_Management_Process.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_traffic_5foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 316 -V 5 o "C:\Users\wvm405\data\logs\test\Sepsis Cases - Event Log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_sepsis_5foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 98  -V 5 o "C:\Users\wvm405\data\logs\test\CoSeLog WABO - Receipt phase of an environmental permit application process.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_wabo_5foldCV-flatexp.dat
