java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 134 -V 3 o C:\Users\wvm405\data\logs\test\dailyactivities_alllogs_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_activitiesLT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 104  -V 3 o "C:\Users\wvm405\data\logs\test\Hospital Billing - Event Log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_billing_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 130 -V 3 o C:\Users\wvm405\data\logs\test\BPI_Challenge_2012_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2012LT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 58  -V 3 o C:\Users\wvm405\data\logs\test\BPI_Challenge_2013_incidents_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2013LT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 40  -V 3 o "C:\Users\wvm405\data\logs\test\DocumentProcessingENG_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_docprocLT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 166 -V 3 o "C:\Users\wvm405\data\logs\test\dreyers_log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_dreyer_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 54  -V 3 o "C:\Users\wvm405\data\logs\test\ElectronicInvoicingENG_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_einvoicingLT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 230 -V 3 o "C:\Users\wvm405\data\logs\test\nasa-cev-complete-splitted_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_nasaLT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 244 -V 3 o "C:\Users\wvm405\data\logs\test\Production_Data_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_productionLT_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 70  -V 3 o "C:\Users\wvm405\data\logs\test\Road_Traffic_Fine_Management_Process.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_traffic_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 66  -V 3 o "C:\Users\wvm405\data\logs\test\Sepsis Cases - Event Log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_sepsis_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 94  -V 3 o "C:\Users\wvm405\data\logs\test\CoSeLog WABO - Receipt phase of an environmental permit application process.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_wabo_3foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 128 -V 3 o "C:\Users\wvm405\data\logs\test\BPI2017_Challenge 2017.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2017_3foldCV-flatexp.dat

