REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 190 -V 2 o C:\Users\wvm405\data\logs\test\dailyactivities_alllogs_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_activitiesLT_2foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 84  -V 2 o "C:\Users\wvm405\data\logs\test\Hospital Billing - Event Log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_billing_2foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 164 -V 2 o C:\Users\wvm405\data\logs\test\BPI_Challenge_2012_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2012LT_2foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 106  -V 2 o C:\Users\wvm405\data\logs\test\BPI_Challenge_2013_incidents_LT.xes >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2013LT_2foldCV-flatexp.dat
REM java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 118 -V 2 o "C:\Users\wvm405\data\logs\test\BPI2017_Challenge 2017.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_BPIC2017_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 36  -V 2 o "C:\Users\wvm405\data\logs\test\DocumentProcessingENG_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_docprocLT_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 168 -V 2 o "C:\Users\wvm405\data\logs\test\dreyers_log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_dreyer_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 50  -V 2 o "C:\Users\wvm405\data\logs\test\ElectronicInvoicingENG_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_einvoicingLT_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 232 -V 2 o "C:\Users\wvm405\data\logs\test\nasa-cev-complete-splitted_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_nasaLT_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 218 -V 2 o "C:\Users\wvm405\data\logs\test\Production_Data_LT.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_productionLT_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 64  -V 2 o "C:\Users\wvm405\data\logs\test\Road_Traffic_Fine_Management_Process.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_traffic_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 66  -V 2 o "C:\Users\wvm405\data\logs\test\Sepsis Cases - Event Log.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_sepsis_2foldCV-flatexp.dat
java -Xmx30G -Xms30G -jar qmpm.jar -fpmTSa 0.1 82  -V 2 o "C:\Users\wvm405\data\logs\test\CoSeLog WABO - Receipt phase of an environmental permit application process.xes" >> C:\Users\wvm405\phd\research\papers\mining-metrics-2019\minerfulautoIM_wabo_2foldCV-flatexp.dat
